export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ERROR_PROJECT = 'ERROR_PROJECT';


export const TASKS_PROJECT = 'TASKS_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const ACTUAL_TASK = 'ACTUAL_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCCESFUL_REGISTRATION = 'SUCCESFUL_REGISTRATION';
export const UNSUCCESFUL_REGISTRATION = 'UNSUCCESFUL_REGISTRATION';
export const GET_USER = 'GET_USER';
export const SUCCESFUL_LOGIN = 'SUCCESFUL_LOGIN';
export const UNSUCCESFUL_LOGIN = 'UNSUCCESFUL_LOGIN';
export const LOG_OUT = 'LOG_OUT';
